title: Raun Kim
description: Portfolio Website

theme: just-the-docs

color_scheme: dark

search_enabled: false

nav_enabled: true

heading_anchors: false

back_to_top: true
back_to_top_text: "Back to top"
